#!/bin/sh

# ssh into webserver as app user
ssh  app@172.31.22.181 <<EOF
  printf "\nAdding dramatic pause\n"
  sleep 30
  cd /var/www/nodes/jawademo
  git pull
  npm install --production
  pm2 restart jawademo
  exit
EOF