#!/bin/sh

# ssh into webserver as app user
ssh  app@172.31.22.181 <<EOF
  printf "\nPausing just to add some drama\n"
  pause 60
  cd /var/www/nodes/jawademo
  git pull
  npm install --production
  pm2 restart jawademo
  exit
EOF